@baseUrl = http://localhost:3000 
###

# @name create_short
POST {{baseUrl}}/link
Content-Type: application/json

{
 "url": "https://www.youtube.com/watch?v=dtwicHIM3dE&t"
}

###

# @name list_shorten
GET {{baseUrl}}/shorten
Content-Type: application/json

### 
# @name redirect
@short_link="deb29b"

GET {{baseUrl}}/shorten/{{short_link}}


### 
# @name delete

DELETE {{baseUrl}}/shorten/b894c0
