services:
  postgres:
    container_name: short-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: short
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  reverse-proxy:
    image: traefik:v3.3
    command:
      - --configFile=/traefik/traefik.toml
    ports:
      - "9000:9000"  # app entrypoint
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik/traefik.toml    
      - ./traefik/conf:/traefik/conf                          
    networks:
      - default

  nest:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

networks:
  default:
    driver: bridge
